import Head from 'next/head';
import styles from '../styles/main.module.css';
import Form from '../components/Form';
import {useState} from 'react';
import ModalLayout from '../components/ModalLayout';
import {CSSTransition} from 'react-transition-group';
import PolicyContent from '../components/PolicyContent';

export default function Home() {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isPolicyOpen, setIsPolicyOpen] = useState(false);
  const [currentUser, setCurrentUser] = useState('');

  const handleModalCloseClick = () => {
    setIsModalOpen(false);
    setTimeout(() => setCurrentUser(''), 300);
  };
  const handlePolicyOpenClick = () => setIsPolicyOpen(true);
  const handlePolicyCloseClick = () => setIsPolicyOpen(false);

  const handleSubmitClick = name => {
    setCurrentUser(name);
    setIsModalOpen(true);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Test Mygento</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Form styles={styles} openPopup={handleSubmitClick} openPolicy={handlePolicyOpenClick} />
        <CSSTransition in={isModalOpen} timeout={300} classNames="popup" unmountOnExit mountOnEnter>
          <ModalLayout
            isSimple
            buttonText="понятно"
            className={styles}
            title={`Спасибо ${currentUser}!`}
            handleClose={handleModalCloseClick}
          >
            <div>Мы скоро свяжемся с вами</div>
          </ModalLayout>
        </CSSTransition>
        <CSSTransition
          in={isPolicyOpen}
          timeout={300}
          classNames="popup"
          unmountOnExit
          mountOnEnter
        >
          <ModalLayout
            buttonText="Я согласен"
            className={styles}
            title="Политика Конфиденциальности"
            handleClose={handlePolicyCloseClick}
            withCross
          >
            <PolicyContent className={styles} />
          </ModalLayout>
        </CSSTransition>
      </main>
    </div>
  );
}
